FROM frolvlad/alpine-glibc:alpine-3.12

RUN apk update && \
    apk add --no-cache curl bash gcc libc-dev make

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup update

WORKDIR /usr/src/app

CMD ["cargo", "run"]
