name: Release Binary and .deb

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build binary
        run: cargo build --release
        working-directory: routing_project

      - name: Build .deb package
        run: cargo deb
        working-directory: routing_project

      - name: Upload binary and .deb to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            routing_project/target/release/routing_project
            routing_project/target/debian/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
